export const ErrorCodes = {
  // Auth
  INVALID_DISPLAY_NAME: 'INVALID_DISPLAY_NAME',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Room
  ALREADY_IN_ROOM: 'ALREADY_IN_ROOM',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  SPECTATORS_FULL: 'SPECTATORS_FULL',
  ROOM_IN_PROGRESS: 'ROOM_IN_PROGRESS',
  NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
  NOT_HOST: 'NOT_HOST',
  PLAYER_KICKED: 'PLAYER_KICKED',
  PLAYER_NOT_IN_ROOM: 'PLAYER_NOT_IN_ROOM',
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  GAME_STARTED: 'GAME_STARTED',
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',

  // Game actions
  INVALID_PHASE: 'INVALID_PHASE',
  INVALID_TARGET: 'INVALID_TARGET',
  WRONG_ROLE: 'WRONG_ROLE',
  PLAYER_DEAD: 'PLAYER_DEAD',
  SELF_TARGET: 'SELF_TARGET',
  ALREADY_INSPECTED: 'ALREADY_INSPECTED',
  CONSECUTIVE_PROTECT: 'CONSECUTIVE_PROTECT',
  WOLF_TARGETING_WOLF: 'WOLF_TARGETING_WOLF',

  // Chat
  RATE_LIMITED: 'RATE_LIMITED',
  CHANNEL_ACCESS_DENIED: 'CHANNEL_ACCESS_DENIED',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',

  // Settings
  INVALID_SETTINGS: 'INVALID_SETTINGS',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
